### ISSUE TITLE
@ALLEY Edit and format current solutions

### ISSUE THREAD

**Issue by lukehoang1905** [coderschool/virgil-web-solutions-public#2]
Format the .md as we discuss
Comment here when you've done

**Comment by allycoderschool** [comment]
New changes commited.

**Comment by lukehoang1905** [comment]
Thank you

**Comment by lukehoang1905** [comment]
Hey where is your work? 
You should push your work here!

**Comment by allycoderschool** [comment]
What's happened to branch patch-1? T.T
