### ISSUE TITLE
[virgil-web-solutions-public/module-1/m11-html&css/layout-challenge.md] Challenge6

### ISSUE THREAD

**Issue by TrinhDucLocUT** [coderschool/virgil-web-solutions-public#32]
Code wrong:
/* Challenge 6 */
#challenge6 .box2 {
  position: absolute;
  right: 0;
  top: 0;
}
#challenge6 .box3 {
  position: absolute;
  left: 0;
  bottom: 0;
}

Code suggest:
#challenge6 .box2 {
  position: absolute;
  left: 0;
  bottom: 0;
}

#challenge6 .box3 {
  position: absolute;
  right: 0;
  top: 0;
}

**Comment by lukehoang1905** [comment]
solve
